language: python
python:
    - "2.7"
# command to install dependencies
install:
    - travis_retry pip install -r requirements-frozen.txt
# command to run tests
env:
  - IS_TRAVIS=true
before_script:
  - npm install -g less
  - psql -c 'CREATE DATABASE kido;' -U postgres
  - psql -c "CREATE USER kido WITH PASSWORD 'kido';" -U postgres
  - python -c 'from app.models import db; db.create_all()'
script: python test.py
# use new travis-ci container-based infrastructure
sudo: false
