language: python
python:
    - "2.7"
# command to install dependencies
install:
    - travis_retry pip install --use-mirrors -r requirements.txt
# command to run tests
script: test.py
# use new travis-ci container-based infrastructure
sudo: false