language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - make installdev
before_script:
  - cp kido/settings/travis.example.py kido/settings/test.py
  - psql -c 'CREATE DATABASE kido;' -U postgres
  - python -c 'from kido.models import db; db.create_all()'
script: make test
sudo: false
