language: python
python:
  - "2.7"
services:
  - postgresql
install:
  - travis_retry pip install -r requirements-frozen.txt
before_script:
  - cp kido/settings/travis.example.py kido/settings/test.py
  - psql -c 'CREATE DATABASE kido;' -U postgres
  - npm install -g less
  - python -c 'from app.models import db; db.create_all()'
script: python test.py
sudo: false
